services:
  postgres:
    image: postgres:15-alpine
    container_name: sos_reparos_db
    environment:
      POSTGRES_DB: sos_reparos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sos_pg_data:/var/lib/postgresql/data

volumes:
  sos_pg_data:
